name: Deploy backend_2 and frontend_2 to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies for backend_2
        run: |
          cd backend_2
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Zip backend artifact for deployment
        run: |
          cd backend_2
          zip -r backend_2.zip . -x "venv/*" "__pycache__/*"

      - name: Upload backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend_2
          path: backend_2/backend_2.zip

  deploy_backend:
    runs-on: ubuntu-latest
    needs: build_backend

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v3
        with:
          name: backend_2

      - name: Deploy backend_2 to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'tech0-gen-6-step4-studentwebapp-11'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}

  build_frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies for frontend_2
        run: |
          cd frontend_2
          npm install

      - name: Build frontend_2
        run: |
          cd frontend_2
          npm run build

      - name: Zip frontend artifact for deployment
        run: |
          cd frontend_2
          zip -r frontend_2.zip .next static public

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend_2
          path: frontend_2/frontend_2.zip

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: build_frontend

    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend_2

      - name: Deploy frontend_2 to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'tech0-gen-6-step4-studentwebapp-12'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_FRONTEND_PUBLISH_PROFILE }}

